name: 部署
on:
  push:
    branches:
      - main
jobs:
  build:
    name: 构建与部署
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 准备 Git 环境
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 准备 Node.js 环境
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: 安装依赖
        uses: pnpm/action-setup@v3
        with:
          run_install: true
      - name: 构建静态站点
        run: pnpm build
      - name: 设置环境
        uses: actions/configure-pages@v2
        with:
          path: dist
      - name: 上传物料
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: 发布线上
        uses: actions/deploy-pages@v1
